### ISSUE TITLE
index.html should be generated with indication that no images yet available when sequence has not yet begun

### ISSUE THREAD

**Issue by pjdubya** [pjdubya/nina-image-data#1]
css and js are created but no index.html so the dashboard tile will not work properly

Possible side effect / separate issue: card is currently getting stuck displaying old index.html when that file is deleted. Not sure why it would be doing that or how to disable the caching.

**Comment by pjdubya** [comment]
Resolved in latest commit

**Comment by chvvkumar** [comment]
I just installed 0.10 and index.html is not showing up under www . Here is myconfig. Any ideas?

![image](https://github.com/pjdubya/nina-image-data/assets/16548147/1ca928f2-f41d-4c2c-856b-902948c947c7)

config/configuration.yaml
```
# -----------------------------------------------------------------------------------
# pyscript
# -----------------------------------------------------------------------------------
pyscript: !include pyscript/config.yaml
```

config/pyscript/config.yaml
```
allow_all_imports: true
apps:
  nina-image-data:
    - nina_web_viewer_base_url: http://astromele.lan:80
      image_folder: /config/www/ApImages
      source_folder: /config/pyscript/apps/nina-image-data/source
```
Calling the service:
![image](https://github.com/pjdubya/nina-image-data/assets/16548147/dc9d4729-c436-474f-9e19-8b5b4192925d)
